
# module load guppy/6.1.2-gpu
# module load dorado

# Input directories
IN_DIR: /gpfs/commons/groups/innovation/dwm/DATA/ont
OUTDIR: /gpfs/commons/groups/innovation/dwm/DATA/ont_recalled

#pION experiments
EXPTS:
  E031: [C1_1mer, C1_1mer_2, D1_1mer, D1_1mer_2]
  E034: [D2_15mer]

# mION experiments
# EXPTS:
#   E026: [C2_14mer]

# Filepath(s) to the dorado models needed
MODELS:
  sup: resources/dorado_models/dna_r10.4.1_e8.2_400bps_sup@v4.3.0

# Run settings
THREADS: 4

# Executables
EXEC:
  GUPPY: guppy_basecaller
  DORADO: dorado
  SAMTOOLS: samtools